"""User-defined mood registry (dynamic room-state taxonomy)."""

from .registry import (
    BUILTIN_MOODS,
    LIFECYCLE_STATES,
    MoodRegistryError,
    MoodValidationError,
    active_mood_ids,
    allowed_live_labels,
    bundle_class_set,
    compute_lifecycle,
    create_mood,
    delete_mood,
    enrich_mood,
    get_mood,
    inference_eligible_labels,
    load_registry,
    save_registry,
    set_consent,
    ui_state_order,
    update_mood_ml,
)

__all__ = [
    "BUILTIN_MOODS",
    "LIFECYCLE_STATES",
    "MoodRegistryError",
    "MoodValidationError",
    "active_mood_ids",
    "allowed_live_labels",
    "bundle_class_set",
    "compute_lifecycle",
    "create_mood",
    "delete_mood",
    "enrich_mood",
    "get_mood",
    "inference_eligible_labels",
    "load_registry",
    "save_registry",
    "set_consent",
    "ui_state_order",
    "update_mood_ml",
]
